const { withXcodeProject, withDangerousMod } = require('@expo/config-plugins');
const fs = require('node:fs');
const path = require('node:path');

/**
 * Adds an XCUITest target to the generated Xcode project.
 *
 * `ios/` is generated by `expo prebuild` and is gitignored, so a target added by
 * hand disappears on the next regeneration. Injecting it here means the target
 * is described in tracked source and rebuilt every time, which is the point of
 * Expo's managed native config.
 *
 * Test sources live in `e2e/MiraUITests/` and are copied in, so they stay
 * reviewable in the repository rather than buried in a generated directory.
 */
const TARGET_NAME = 'MiraUITests';
const SOURCE_DIR = path.join('e2e', TARGET_NAME);
const UI_TESTING_PRODUCT_TYPE = 'com.apple.product-type.bundle.ui-testing';

const swiftFilesIn = (dir) => fs.readdirSync(dir).filter((f) => f.endsWith('.swift')).sort();

/** Copy the tracked Swift sources into the generated project. */
const withUITestSources = (config) =>
  withDangerousMod(config, [
    'ios',
    async (cfg) => {
      const from = path.join(cfg.modRequest.projectRoot, SOURCE_DIR);
      const to = path.join(cfg.modRequest.platformProjectRoot, TARGET_NAME);

      if (!fs.existsSync(from)) {
        throw new Error(`withUITestTarget: missing test sources at ${SOURCE_DIR}`);
      }

      fs.rmSync(to, { recursive: true, force: true });
      fs.mkdirSync(to, { recursive: true });
      for (const file of swiftFilesIn(from)) {
        fs.copyFileSync(path.join(from, file), path.join(to, file));
      }

      fs.writeFileSync(
        path.join(to, 'Info.plist'),
        `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDevelopmentRegion</key><string>$(DEVELOPMENT_LANGUAGE)</string>
  <key>CFBundleExecutable</key><string>$(EXECUTABLE_NAME)</string>
  <key>CFBundleIdentifier</key><string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
  <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
  <key>CFBundleName</key><string>$(PRODUCT_NAME)</string>
  <key>CFBundlePackageType</key><string>BNDL</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundleVersion</key><string>1</string>
</dict>
</plist>
`,
      );

      return cfg;
    },
  ]);

/** Register the target, its sources, and its dependency on the app. */
const withUITestPbxTarget = (config) =>
  withXcodeProject(config, (cfg) => {
    const project = cfg.modResults;
    const appName = cfg.modRequest.projectName;
    if (!appName) throw new Error('withUITestTarget: no projectName');

    // Idempotent: prebuild runs repeatedly, and a duplicate target produces a
    // project Xcode refuses to open.
    if (project.pbxTargetByName(TARGET_NAME)) return cfg;

    // The `xcode` package predates UI-test bundles and only knows
    // `unit_test_bundle`. Both produce a `wrapper.cfbundle`, so its machinery
    // builds the right structure and only the product type needs correcting.
    const target = project.addTarget(
      TARGET_NAME,
      'unit_test_bundle',
      TARGET_NAME,
      `${cfg.ios?.bundleIdentifier ?? 'app.mira.ios'}.uitests`,
    );

    const nativeTargets = project.pbxNativeTargetSection();
    if (nativeTargets[target.uuid]) {
      nativeTargets[target.uuid].productType = `"${UI_TESTING_PRODUCT_TYPE}"`;
    }

    project.addBuildPhase([], 'PBXSourcesBuildPhase', 'Sources', target.uuid);
    project.addBuildPhase([], 'PBXFrameworksBuildPhase', 'Frameworks', target.uuid);

    const targetDir = path.join(cfg.modRequest.platformProjectRoot, TARGET_NAME);
    const sources = swiftFilesIn(targetDir);

    // Created EMPTY: `addPbxGroup` would create its own file references, and
    // `addSourceFile` below creates them again — the duplicates then fight.
    const group = project.addPbxGroup([], TARGET_NAME, TARGET_NAME);

    // Hang the group off the project root so it is visible in Xcode.
    const groups = project.hash.project.objects.PBXGroup;
    for (const key of Object.keys(groups)) {
      const entry = groups[key];
      if (entry && !entry.name && !entry.path && entry.children) {
        project.addToPbxGroup(group.uuid, key);
        break;
      }
    }

    for (const file of sources) {
      // Just the basename: the group already carries `path = MiraUITests`, and
      // prefixing it again resolves to MiraUITests/MiraUITests/<file>.
      project.addSourceFile(file, { target: target.uuid }, group.uuid);
    }

    // The tests need the app built first, and must know which app they drive.
    // `pbxTargetByName` returns the target object without its uuid, so the uuid
    // is looked up from the native target section directly.
    const appTargetUuid = Object.keys(nativeTargets).find(
      (key) => !key.endsWith('_comment') && nativeTargets[key]?.name === appName,
    );
    if (appTargetUuid) {
      project.addTargetDependency(target.uuid, [appTargetUuid]);
    }

    const configurations = project.pbxXCBuildConfigurationSection();
    for (const key of Object.keys(configurations)) {
      const settings = configurations[key]?.buildSettings;
      if (!settings || settings.PRODUCT_NAME !== `"${TARGET_NAME}"`) continue;

      settings.TEST_TARGET_NAME = `"${appName}"`;
      settings.SWIFT_VERSION = '5.0';
      // 17.0, not the app's 16.4: `performAccessibilityAudit()` requires it,
      // and the test bundle never ships — it only ever runs on a simulator we
      // control.
      settings.IPHONEOS_DEPLOYMENT_TARGET = '17.0';
      settings.CODE_SIGN_STYLE = 'Automatic';
      settings.TARGETED_DEVICE_FAMILY = '"1,2"';
      settings.INFOPLIST_FILE = `"${TARGET_NAME}/Info.plist"`;
      settings.LD_RUNPATH_SEARCH_PATHS =
        '"$(inherited) @executable_path/Frameworks @loader_path/Frameworks"';
      settings.ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = 'YES';
    }

    patchScheme(cfg.modRequest.platformProjectRoot, appName, target.uuid);

    return cfg;
  });

/**
 * Add the target to the shared scheme's test action.
 *
 * Called from inside the xcodeproj mod, not as a separate dangerous mod: Expo
 * runs dangerous mods BEFORE xcodeproj ones, so a separate mod would read a
 * pbxproj that does not yet contain the target and silently do nothing.
 * The scheme is a plain file, so writing it here is safe.
 */
function patchScheme(platformProjectRoot, appName, targetUuid) {
  const schemePath = path.join(
    platformProjectRoot,
    `${appName}.xcodeproj`,
    'xcshareddata',
    'xcschemes',
    `${appName}.xcscheme`,
  );
  if (!fs.existsSync(schemePath)) return;

  let scheme = fs.readFileSync(schemePath, 'utf8');
  if (scheme.includes(TARGET_NAME)) return;

  const testable = `      <TestableReference
         skipped = "NO">
         <BuildableReference
            BuildableIdentifier = "primary"
            BlueprintIdentifier = "${targetUuid}"
            BuildableName = "${TARGET_NAME}.xctest"
            BlueprintName = "${TARGET_NAME}"
            ReferencedContainer = "container:${appName}.xcodeproj">
         </BuildableReference>
      </TestableReference>
`;

  if (scheme.includes('</Testables>')) {
    scheme = scheme.replace('</Testables>', `${testable}      </Testables>`);
  } else {
    scheme = scheme.replace(
      /(<TestAction[^>]*>)/,
      `$1\n      <Testables>\n${testable}      </Testables>`,
    );
  }

  fs.writeFileSync(schemePath, scheme);
}

module.exports = (config) => withUITestPbxTarget(withUITestSources(config));
